name: meta_business
description: temp_package_description

version: 1.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  get_it: ^7.6.0
  easy_localization: ^3.0.2
  go_router: ^10.0.0
  flutter_screenutil: ^5.8.4

  cupertino_icons: ^1.0.5
  dio: ^5.3.0
  logger: ^1.4.0
  connectivity_plus: ^4.0.1
  hive: ^3.0.0-dev
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  image_picker: ^1.0.1
  image_cropper: ^5.0.0
  flutter_keyboard_visibility: ^5.4.1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  google_fonts: ^5.1.0
  file: ^6.1.4
  url_strategy: ^0.2.0
  flutter_portal: ^1.1.4
  flutter_native_splash: ^2.3.1
  dotted_border: ^2.0.0+3
  intl: ^0.18.1
  timezone: ^0.8.0
  gap: ^3.0.1
  flutter_switch: ^0.3.2

  word_generator: ^0.4.3
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
    
  _iwu_pack:
    # path: ../imagineeringwithus_packclear
  dart_ipify: ^1.1.1

dependency_overrides:
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
 
  auto_route_generator: ^7.2.0
  build_runner:   

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/png/logo_1024.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 
